function scp_breedpad_reset_values() {
	//reset breed values
	//gender
	for(aa=0;aa<2;aa++){    //male and female values
		aerodactyl[aa]=0
	    alakazam[aa]=0
	    arcanine[aa]=0
		arbok[aa]=0
		blissey[aa]=0
		beedrill[aa]=0
	    blastoise[aa]=0
	    butterfree[aa]=0
	    charizard[aa]=0
	    cloyster[aa]=0
		crobat[aa]=0
		dewgong[aa]=0
		dodrio[aa]=0
		dugtrio[aa]=0
		electivire[aa]=0
		exeggutor[aa]=0
		farfetched[aa]=0
	    fearow[aa]=0
		goldeen[aa]=0
	    golduck[aa]=0
		gyarados[aa]=0
		houndoom[aa]=0
		hypno[aa]=0
		jynx[aa]=0
		kangaskhan[aa]=0
		kingdra[aa]=0
		kingler[aa]=0
		lickilicky[aa]=0
	    machamp[aa]=0
		magmortar[aa]=0
		mew[aa]=0
		miltank[aa]=0
	    nidoqueen[aa]=0
	    ninetails[aa]=0
	    parasect[aa]=0
	    persian[aa]=0
	    pidgeot[aa]=0
		pinsir[aa]=0
	    poliwrath[aa]=0				
	    primeape[aa]=0
	    raichu[aa]=0
	    rapidash[aa]=0
	    raticate[aa]=0
		rhyperior[aa]=0
	    sandslash[aa]=0
		sceptile[aa]=0
		scizor[aa]=0
		slowking[aa]=0
		starmie[aa]=0
		tangrowth[aa]=0
	    tentacruel[aa]=0
		togekiss[aa]=0
	    torkoal[aa]=0
		ursaring[aa]=0
	    venomoth[aa]=0
	    venusaur[aa]=0
	    victreebell[aa]=0
		vileplume[aa]=0
	    wigglytuff[aa]=0
    
		//eevee
	    eevee[aa]=0;   
	        flareon[aa]=0;   
	        jolteon[aa]=0;  
	        vaporeon[aa]=0; 
	        espeon[aa]=0;   
	        umbreon[aa]=0; 
			
		//genderless
	    electrode=0;
	    gengar=0;
		golem=0;
		magnezone=0;
		muk=0;
	    steelix=0;
		hitmon=0;
		weezing=0;
	}
}
